# h2 데이터베이스 설정
spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      # 어플리케이션 실행 시점에 테이블을 drop 하고 다시 생성
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        # 지연로딩 성능 최적화
        default_batch_fetch_size: 100

logging:
  level:
    # logger 를 통해 하이버네이트 실행 sql 을 남김
    org.hibernate.SQL: debug
#    org.hibernate.type: trace

